---
- hosts: all
  roles:

  - role: zsh
  - role: maximum_awesome

  - role: git
    git_user_name: Sahn Lam
    git_user_email: sahn@pobox.com
  - role: rbenv

  - role: brew_package
    package_name: mercurial
  - role: brew_package
    package_name: clipper
  - role: brew_package
    package_name: gnu-tar

  - role: cask_package
    package_name: dropbox
  - role: cask_package
    package_name: onepassword
  - role: cask_package
    package_name: alfred
  - role: cask_package
    package_name: menumeters
  - role: cask_package
    package_name: google-chrome
  - role: cask_package
    package_name: firefox
  - role: cask_package
    package_name: virtualbox
  - role: cask_package
    package_name: vagrant
  - role: cask_package
    package_name: wireshark
  - role: cask_package
    package_name: gitx
  - role: cask_package
    package_name: asepsis

  # osx config
  - role: dock
    apps:
    - "/Applications/Google Chrome.app"
    - /Applications/Firefox.app
    - /Applications/iTerm.app
    folders:
    - path: ~/
    - path: ~/Documents
    - path: ~/Downloads
      sort: datemodified
  - role: dashboard
    disabled: YES

